export const list = [
  { title: 'agree', type: 'infinitive' },
  { title: 'allow', type: 'infinitive' },
  { title: 'appear', type: 'infinitive' },
  { title: 'arrange', type: 'infinitive' },
  { title: 'ask', type: 'infinitive' },
  { title: 'choose', type: 'infinitive' },
  { title: 'decide', type: 'infinitive' },
  { title: 'demand', type: 'infinitive' },
  { title: 'encourage', type: 'infinitive' },
  { title: 'fail', type: 'infinitive' },
  { title: 'forbid', type: 'infinitive' },
  { title: 'force', type: 'infinitive' },
  { title: 'hope', type: 'infinitive' },
  { title: 'instruct', type: 'infinitive' },
  { title: 'invite', type: 'infinitive' },
  { title: 'learn', type: 'infinitive' },
  { title: 'manage', type: 'infinitive' },
  { title: 'offer', type: 'infinitive' },
  { title: 'order', type: 'infinitive' },
  { title: 'permit', type: 'infinitive' },
  { title: 'persuade', type: 'infinitive' },
  { title: 'plan', type: 'infinitive' },
  { title: 'prepare', type: 'infinitive' },
  { title: 'pretend', type: 'infinitive' },
  { title: 'promise', type: 'infinitive' },
  { title: 'refuse', type: 'infinitive' },
  { title: 'remind', type: 'infinitive' },
  { title: 'seem', type: 'infinitive' },
  { title: 'swear', type: 'infinitive' },
  { title: 'warn', type: 'infinitive' },

  { title: 'be about', type: 'infinitive', variant: 'expression' },
  { title: 'do one\'s best', type: 'infinitive', variant: 'expression' },
  { title: 'make up one\'s mind', type: 'infinitive', variant: 'expression' },
  { title: 'set out', type: 'infinitive', variant: 'expression' },
  { title: 'turn out', type: 'infinitive', variant: 'expression' },

  { title: 'admit', type: 'gerund' },
  { title: 'consider', type: 'gerund' },
  { title: 'delay', type: 'gerund' },
  { title: 'dislike', type: 'gerund' },
  { title: 'enjoy', type: 'gerund' },
  { title: 'escape', type: 'gerund' },
  { title: 'excuse', type: 'gerund' },
  { title: 'finish', type: 'gerund' },
  { title: 'forgive', type: 'gerund' },
  { title: 'imagine', type: 'gerund' },
  { title: 'insist', type: 'gerund' },
  { title: 'keep', type: 'gerund' },
  { title: 'mind', type: 'gerund' },
  { title: 'miss', type: 'gerund' },
  { title: 'practise', type: 'gerund' },
  { title: 'prevent', type: 'gerund' },
  { title: 'risk', type: 'gerund' },
  { title: 'suggest', type: 'gerund' },
  { title: 'understand', type: 'gerund' },

  { title: 'be against', type: 'gerund', variant: 'expression' },
  { title: 'be interested in', type: 'gerund', variant: 'expression' },
  { title: 'can\'t stand', type: 'gerund', variant: 'expression' },
  { title: 'can\'t help', type: 'gerund', variant: 'expression' },
  { title: 'care for', type: 'gerund', variant: 'expression' },
  { title: 'give up', type: 'gerund', variant: 'expression' },
  { title: 'look forward to', type: 'gerund', variant: 'expression' },
  { title: 'it\'s no use/good', type: 'gerund', variant: 'expression' },
  { title: 'it\'s worth', type: 'gerund', variant: 'expression' },

  { title: 'begin', type: 'gerund_infinitive' },
  { title: 'start', type: 'gerund_infinitive' },
  { title: 'continue', type: 'gerund_infinitive' },
  { title: 'can\'t bear', type: 'gerund_infinitive' },
  { title: 'intend', type: 'gerund_infinitive' },
  { title: 'advise', type: 'gerund_infinitive' },
  { title: 'recommend', type: 'gerund_infinitive' },
  { title: 'it needs', type: 'gerund_infinitive' },
  { title: 'it requires', type: 'gerund_infinitive' },
  { title: 'it wants', type: 'gerund_infinitive' },

  { title: 'Remember', type: 'gerund_infinitive', variant: 'different_meaning' },
  { title: 'Try', type: 'gerund_infinitive', variant: 'different_meaning' },
  { title: 'Love/like/hate/prefer', type: 'gerund_infinitive', variant: 'different_meaning' },
  { title: 'Go on', type: 'gerund_infinitive', variant: 'different_meaning' },
  { title: 'Stop', type: 'gerund_infinitive', variant: 'different_meaning' },
  { title: 'Mean', type: 'gerund_infinitive', variant: 'different_meaning' },
  { title: 'Be afraid', type: 'gerund_infinitive', variant: 'different_meaning' },
  { title: 'I\'m sorry', type: 'gerund_infinitive', variant: 'different_meaning' },
];

// permit, allow
