export const VOCAB_CORRECT_ANSWERS = 'VOCAB_CORRECT_ANSWERS';
export const VOCAB_INCORRECT_ANSWERS = 'VOCAB_INCORRECT_ANSWERS';
export const PHRASAL_VERBS_CORRECT_ANSWERS = 'PHRASAL_VERBS_CORRECT_ANSWERS';
export const PHRASAL_VERBS_INCORRECT_ANSWERS = 'PHRASAL_VERBS_INCORRECT_ANSWERS';
